name: OS Compatibility Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  comp_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022, macos-13, macos-14]
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: '{{cookiecutter.python_version}}'
          enable-cache: true
      - run: uv tool install branthebuilder
      - run: branb test
